routes/web.php
<?php

use App\Http\Controllers\User\EmailController;
use App\Http\Controllers\User\UserAnnouncementController;
use GuzzleHttp\Middleware;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::get('/search', [App\Http\Controllers\HomeController::class, 'search'])->name('search');
Route::get('/announcementByCategory/{id}', [App\Http\Controllers\HomeController::class, 'searchByCategory'])->name('searchByCategory');


Route::get('/contacts', [App\Http\Controllers\PageController::class, 'contacts'])->name('contacts');
Route::post('/locale/{locale}', [App\Http\Controllers\PageController::class, 'locale'])->name('locale');

Route::post('/sendEmail', [EmailController::class, 'sendEmail'])->name('sendEmail');



Route::post('/register', [App\Http\Controllers\Auth\RegisteredUserController::class, 'store'])->name('register');


Route::prefix('user-announcement')->name('user.')->group( function ()
{
    Route::resource('announcement', App\Http\Controllers\User\UserAnnouncementController::class);
});
Route::post('/announcement/images/upload', [UserAnnouncementController::class, 'uploadImage'])->name('announcement.images.upload');
Route::delete('/announcement/images/remove', [UserAnnouncementController::class, 'deleteImage'])->name('announcement.images.delete');
Route::get('/announcement/images', [UserAnnouncementController::class, 'getImages'])->name('announcement.images');


Route::prefix('revisor-announcement-managment')->name('revisor.')->group( function ()
{
    Route::post('/accept/{announcement}', [App\Http\Controllers\Revisor\RevisorAnnouncementController::class, 'acceptAnnouncement'])->name('acceptAnnouncement');
    Route::post('/reject/{announcement}', [App\Http\Controllers\Revisor\RevisorAnnouncementController::class, 'rejecttAnnouncement'])->name('rejecttAnnouncement');
    Route::post('/restore/{announcement}', [App\Http\Controllers\Revisor\RevisorAnnouncementController::class, 'restoreAnnouncement'])->name('restoreAnnouncement');
    Route::post('/delete/{announcement}', [App\Http\Controllers\Revisor\RevisorAnnouncementController::class, 'deleteAnnouncement'])->name('deleteAnnouncement');

    Route::get('/AnnouncementsRevisor', [App\Http\Controllers\Revisor\RevisorAnnouncementController::class, 'index'])->name('index');
});

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable implements MustVerifyEmail
{
    use HasApiTokens, HasFactory, Notifiable;


    /**
     * The attributes that are mass assignable.
     *
     * @var string[]
     */
    protected $fillable = [
        'name',
        'email',
        'password',
        'role_id',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];


    public function hasRole($role)
    {
        return $this->role->code == $role;
    }



    public function role()
    {
        return $this->belongsTo('App\Models\Role');
    }

    public function announcements()
    {
        return $this->hasMany(Announcement::class,'user_id','id');
    }
}

app/Models/announcement.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Storage;
use Laravel\Scout\Searchable;

class Announcement extends Model
{
    use HasFactory,Searchable;

    protected $fillable =
    [
        'title',
        'body',
        'is_accepted',
        'price',
        'user_id',
        'categorie_id',
        'slug',
    ];

     protected $with =
    [
        'category',
        'user',
        'images',
    ];

    public function toSearchableArray()
    {
        $category = $this->category;
        $user = $this->user;

        $array = [
            'id'            => $this->id,
            'title'         => $this->title,
            'body'          => $this->body,
            'category'      => $category,
            'user'      => $user,
        ];

        return $array;
    }

    public function setTitleAttribute($value) //nome colonna grande tra set e attribute, il contenuto verrà catturato e verrà eseguita l'extra logica
    {
        return $this->attributes['title'] = strtoupper($value);
    }

    public function setPriceAttribute($value) //nome colonna grande tra set e attribute, il contenuto verrà catturato e verrà eseguita l'extra logica
    {
        return $this->attributes['price'] = $value.'€';
    }

    public static function announcementsAcceptedCount()
    {
        return Announcement::where('is_accepted',null)->count();
    }


    public function scopeSelectAnnouncements($query,$status)
    {
        return $query = $query->orderBy('created_at','desc')->where('is_accepted',$status);
    }



    public function user()
    {
        return $this->belongsTo(User::class,'user_id','id');
    }

    public function category()
    {
        return $this->belongsTo(Category::class,'categorie_id','id');
    }

    public function images()
    {
        return $this->hasMany('App\Models\AnnouncementImage');
    }



    public function getRouteKeyName()
    {
        return 'slug';
    }

}

app/Http/Controllers/User/EmailController.php
<?php

namespace App\Http\Controllers\User;

use App\Http\Controllers\Controller;
use App\Http\Requests\EmailUserCreateRequest;
use App\Mail\UserRequestRevisor;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Mail;

class EmailController extends Controller
{
    public function sendEmail(EmailUserCreateRequest $request)
    {
        $user = Auth::user();

        $emailBody = $request->email;
        Mail::to('angelosottiled31@hotmail.it')->send(new UserRequestRevisor($emailBody,$user->email));

        return redirect()->route('home')->with("success", (__('ui.successEmail')));
    }
}

app/Http/Controllers/User/UserAnnouncementController.php
<?php

namespace App\Http\Controllers\User;

use App\Http\Controllers\Controller;
use App\Http\Requests\CreateAnnouncementRequest;
use App\Jobs\AddWatermark;
use App\Jobs\GoogleVisionLabelImage;
use App\Jobs\GoogleVisionSafeSearchImage;
use App\Jobs\GoogleVisioRemoveFaces;
use App\Jobs\ResizeImage;
use App\Models\Announcement;
use App\Models\AnnouncementImage;
use App\Models\Category;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\File;
use Illuminate\Support\Facades\Storage;
use Spatie\Image\Image;
use Spatie\Image\Manipulations;

class UserAnnouncementController extends Controller
{
    public function __construct()
    {
        $this->middleware('verified')->except(['show','searchByCategory']);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Request $request)
    {
        $categories = Category::all();


        $uniqueSecret = $request->old('uniqueSecret', base_convert( sha1( uniqid( mt_rand() ) ), 16,36 ) );

        return view('User.Announcement.create',compact('categories','uniqueSecret'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CreateAnnouncementRequest $request)
    {
        try
        {
            DB::beginTransaction();

                $user = Auth::user();

                $announcement = $user->announcements()->create(
                    [
                        'title'  => $request->title,
                        'body'  => $request->body,
                        'price' => $request->price,
                        'slug'  => uniqid(),
                    ]
                ); //se questa viene eseguita   ->    annullata
                //CRASH
                $announcement->category()->associate($request->categories); //questa torna indietro
                $announcement->save();

                $uniqueSecret = $request->uniqueSecret;

                $images = session()->get("images.{$uniqueSecret}",[]); //se non sono stati settati verrà preso un array vuoto
                $removedImages = session()->get("removedImages.{$uniqueSecret}",[]); //se non sono stati settati verrà preso un array vuoto

                $images = array_diff($images,$removedImages); //prendiamo solo le immagini presenti in temp

                if($images)
                {
                    foreach($images as $image)
                    {
                        $amnouncementImage = new AnnouncementImage(); //ci creiamo l'immagine

                        $fileName = basename($image); //dentro image c'è il path, con basename prendiamo solo il nome
                        $newFileName = "public/announcements/{$announcement->id}/{$fileName}"; //il nuovo path dove deve andare l'immagine
                        $moved = Storage::move($image,$newFileName); //lo muoviamo dalla cartella temp alla nuova cartelal con l'id dell'annuncio

                        if($moved)
                        {   //questi vengono fatti uno dopo l'altro
                            $amnouncementImage->file = $newFileName;
                            $amnouncementImage->announcement_id = $announcement->id;
                            $amnouncementImage->save();
                            //questi vengono fatti uno dopo l'altro

                            GoogleVisionSafeSearchImage::withChain( //mentre quelle sopra stanno facendo, si atttivano piano piano anche queste
                                [
                                    new GoogleVisionLabelImage( $amnouncementImage->id ),
                                    new GoogleVisioRemoveFaces( $amnouncementImage->id ),
                                    new ResizeImage($amnouncementImage->file,300,150),
                                ]
                            )->dispatch( $amnouncementImage->id);
                            //se io scrivo qua del codice, verrà processato senza la sicurezza che i jobs dietro siano terminati
                        }
                        else
                        {
                            return redirect()->route('home')->with('error',(__('ui.announcementPubblishError')));
                        }
                    }

                    File::deleteDirectory(storage_path("/app/public/temp/{$uniqueSecret}"));
                }

            DB::commit();

                return redirect()->route('home')->with('success',(__('ui.announcementPubblish')));

        }
        catch(\Exception $e)
        {

            $errors =
            [
                'error_message' => (__('ui.announcementPubblishError')),
            ];

            session()->flash('error',$errors);
            return redirect()->route('home');

        }

    }

    public function deleteImage(Request $request)
    {
        $uniqueSecret = $request->uniqueSecret; // il form LE IMMAGINI SONO CONSERVATE IN UNA CARTELLE AVENTE IL NOME DEL FORM

        $fileName = $request->id; //PATH
        //poichè l'immagine prima di essere stata cancellata è stata inserita nello storage, si dovrà creare un un nuovo array contenente
        //le immagine scartate in modo da eliminare quelle duplicate
        session()->push("removedImages.{$uniqueSecret}",$fileName);

        Storage::delete($fileName);

        return response()->json('ok');
    }


    public function getImages(Request $request)
    {
        //dd($request->all());

        $uniqueSecret = $request->uniqueSecret;

        $images = session()->get("images.{$uniqueSecret}",[]);
        $removedImages = session()->get("removedImages.{$uniqueSecret}",[]);

        $images = array_diff($images,$removedImages);

        $data = [];

        foreach($images as $image)
        {
            $data[] =
            [
                'id'    => $image,
                'src'   => AnnouncementImage::getUrlByFilePath($image,80,80)
            ];
        }

        return response()->json($data);
    }

    public function uploadImage(Request $request)
    {
        $uniqueSecret = $request->uniqueSecret; //questo è passato dalla richiesta in announcementImages.js

        $fileName = $request->file('file')->store("public/temp/{$uniqueSecret}"); //ogni volta che si clicca su un nuovo file verrà inserito nella cartella con il nome del uniqueSecret

        dispatch(new ResizeImage(
            $fileName,
            80,
            80
        ));

        session()->push("images.{$uniqueSecret}",$fileName); // oltre a mettere i file nello store, li mettiamo in sessione

        return response()->json(
            [
                'id'    =>  $fileName, //ritorniamo il path del file sotto nome 'id', questo serve SOLO per identificare quell'immagine in modo da cancellarla, o riprenderla
            ]
        );
    }


    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Announcement $announcement)
    {
        return view('User.announcement.show',compact('announcement'));
    }


    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/User/Announcement/create.blade.php
<x-layout>

    <div class="my-separator"> </div>
    <div class="container col-md-10 col-md-offset-2">
        <div class="card mt-5">
            <div class="card-header ">
                <h5 class="float-left">{{ __('ui.createAnnouncement') }}</h5>
                <a href="{{ route('user.announcement.index') }}" class="btn btn-warning">{{ __('ui.allAnnouncements') }}</a>
            </div>
            <div class="card-body mt-2">
                <form method="post" action="{{ route('user.announcement.store') }}">
                    @csrf

                    <input type="hidden" name="uniqueSecret" value="{{ $uniqueSecret }}">

                    @if ($errors->any())
                        <div class="alert alert-danger">
                            <ul>
                                @foreach ($errors->all() as $error)
                                    <li>{{ $error }}</li>
                                @endforeach
                            </ul>
                        </div>
                    @endif

                    <div class="form-group">
                        <label for="title" class="col-lg-12 control-label">{{ __('ui.title') }}</label>
                        <div class="col-lg-12">
                            <input type="text" class="form-control" id="title" placeholder="{{ __('ui.title') }}" name="title" value="{{old('title') }}">
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="body" class="col-lg-12 control-label">{{ __('ui.body') }}</label>
                        <textarea class="form-control" placeholder="{{ __('ui.body') }}" name="body">{{ old('body') }}</textarea>
                    </div>

                    <div class="form-group">
                        <label for="price" class="col-lg-12 control-label">{{ __('ui.price') }}</label>
                        <div class="col-lg-12">
                            <input type="number" class="form-control" id="price" placeholder="{{ __('ui.title') }}" name="price" value="{{old('price') }}">
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="categories" class="col-lg-12 control-label">{{ __('ui.categories') }}</label>
                        <div class="col-lg-12">
                            <select class="form-control" id="category" name="categories">
                                @foreach($categories as $category)
                                    <option value="{{ $category->id }}">
                                        {{ $category->name }}
                                    </option>
                                @endforeach
                            </select>
                        </div>
                    </div>

                    <div class="form-group">

                        <label for="images" class="col-md-12 col-form-label text-md-right">{{ __('ui.images') }}</label>

                        <div class="col-md-12">
                            <div class="dropzone" id="drophere"></div> <!-- creo il componente con questo id-->

                            @error('images')
                                <span class="invalid-feedback" role="alert">
                                    <strong> {{ $message }} </strong>
                                </span>
                            @enderror
                        </div>

                    </div>

                    <div class="form-group">
                        <div class="col-lg-10 col-lg-offset-2">
                            <button type="submit" class="btn btn-primary">{{ __('ui.submit') }}</button>
                        </div>
                    </div>

                </form>
            </div>
        </div>
    </div>

</x-layout>

resources/views/User/Announcement/show.blade.php
<x-layout>

    <div class="my-separator"> </div>
    <section class="mainShow d-flex flex-column justify-content-around">

        <div class="my-card p-3">
            <div class="row justify-content-between"><!--intestazione -->
                <div class="col-5"><!--User -->
                    <div>
                        <h3 class=""><i class="fas fa-user-circle"></i> {{$announcement->user->name}}</h3>
                    </div>
                </div>
                <div class="col-5 text-end p-2 me-3"><!--data-->
                    <h3 class="fs-6">{{$announcement->created_at->format('Y-m-d')}}</h3>
                </div>
            </div>
                <div id="secondImage">
                    <img src="{{ $announcement->images[0]->getUrl(300,150) }}" class="" alt="">
                </div>

            <div class=""><!--scheda prodotto -->
                <div class="row">
                    <div class="col-12 col-md-8"><!--Titolo -->
                        <div>
                            <h2 class="card-title mt-2 p-2 fw-bold">{{$announcement->title}}</h2>
                        </div>
                    </div>
                    <div class="col-12 col-md-4 text-center align-items-center p-2 mr-2"><!--categoria -->
                        <a href="{{ route('searchByCategory',$announcement->category) }}" class="categoryLink">
                            {{$announcement->name}}
                        </a>
                    </div>
                    <div class="col-12"><!--descrizione accordion -->
                        <div class="accordion accordion-flush" id="accordionFlushExample">
                            <div class="accordion-item  bg-transparent"><!--background descrizione -->
                              <h2 class="accordion-header" id="flush-headingOne">
                                <button class="accordion-button collapsed bg-transparent" type="button" data-bs-toggle="collapse" data-bs-target="#flush-collapseOne" aria-expanded="false" aria-controls="flush-collapseOne">
                                  Dettagli
                                </button>
                              </h2>
                              <div id="flush-collapseOne" class="accordion-collapse collapse" aria-labelledby="flush-headingOne" data-bs-parent="#accordionFlushExample">
                                <div class="accordion-body"><a href="{{ route('user.announcement.show',$announcement) }}" class="goTo"> <p class="card-text cardBody fs-4">{{$announcement->body}}</p> </a></div>
                              </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-4"><!--prezz0 -->
                        <h3 class="info">{{$announcement->price}}</h3>

                    </div>
                    <div class="col-8 text-end"><!--bottone carrello -->
                        <button type="button" class="btn btn-warning">Aggiungi al carrello</button>
                    </div>

                </div>

            </div>
        </div>


        <div class="container-fluid caroulseShow">

            <div class="row justify-content-center h-100">
                <div class="col-6 h-100">
                    <div id="carouselExampleIndicators" class="carousel slide h-100" data-bs-ride="carousel">
                        <div class="carousel-indicators">
                            @for ($i = 0; $i < $announcement->images->count(); $i++)
                                <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="{{ $i }}" class="@if($i == 0) active @endif" aria-current="true" aria-label="Slide {{ $i+1 }}"></button>
                            @endfor
                        </div>
                        <div class="carousel-inner h-100">
                            @foreach ($announcement->images as $i => $image)
                                    <div class="carousel-item @if($i == 0) active @endif">
                                        <img src="{{ $image->getUrl(300,150) }}" class="d-block w-100" alt="..." id="imgCarousel">
                                    </div>
                            @endforeach
                        </div>
                        <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="prev">
                        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                        <span class="visually-hidden">Previous</span>
                        </button>
                        <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="next">
                        <span class="carousel-control-next-icon" aria-hidden="true"></span>
                        <span class="visually-hidden">Next</span>
                        </button>
                    </div>
                </div>
            </div>

        </div>
    </section>




</x-layout>